# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

version: '3'
services:

  app:
    image: pyworkplace-app-test:0.0.0
    environment: &environment
      - STAGE=test
    build:
      args:
        stage: test
        version: 0.0.0
    volumes:
      - .:/usr/src
